### ISSUE TITLE
Slow change of language.

### ISSUE THREAD

**Issue by a-shodipo** [vkucukcakar/jquery-sls#1]
Hi,

So I love this plugin very much but I have an issue. When I switch language the page hangs for 30 sec or more. Is there a way to optimise this?

**Comment by vkucukcakar** [comment]
Hi,

Did you tried the example at?: https://vkucukcakar.github.io/jquery-sls/
It takes milliseconds to change the language. Actually it's usually impossible to see the transformation.

**Comment by vkucukcakar** [comment]
Hi,

Did you try the example at?: https://vkucukcakar.github.io/jquery-sls/
It takes milliseconds to change the language. Actually it's usually impossible to see the transformation.

**Comment by a-shodipo** [comment]
Ok. Thanks. Got it to work right.
